#!/bin/bash
# config de code serveur pour l'ada
sudo apt install gnat -y
cp p_esiut.ad* /usr/lib/gcc/x86_64-linux-gnu/8/adainclude/ 

curl -fsSL https://code-server.dev/install.sh | sh



$ali="alias mada='gnatmake -gnatv -gnato'"
echo $ali >> ~/.bash_aliases
$ali="alias cada='gnatgcc -c -gnatv -gnato'"
echo $ali >> ~/.bash_aliases
source ~/.bashrc


code-server

